"""
摄影机构建器使用的所有数据常量：
  PARAMS_REAL / PARAMS_ANIME   — 基础参数下拉选项
  FILTER_KEYWORDS              — 滤镜积木词库
  SHOT_SCALE                   — 景别滑条选项
  CAMERA_ELEVATION             — 俯仰角滑条选项
  SUBJECT_ANGLE                — 主体方位角滑条选项
  PRESETS_REAL / PRESETS_ANIME — 预设字典
"""

# 实拍模式基础参数  {显示名: (选项列表, keyword提取函数)}
PARAMS_REAL = {
    "镜头焦距":  (["14mm (超广角)", "24mm (广角)", "35mm (标准广角)", "50mm (标准)",
                   "85mm (人像)", "100mm (微距)", "135mm (长焦)", "200mm (远摄)", "400mm (超长焦)"],
                  lambda v: v.split()[0]),
    "光圈":      (["f/1.2", "f/1.4", "f/1.8", "f/2.0", "f/2.8", "f/4", "f/5.6", "f/8", "f/11", "f/16"],
                  lambda v: v),
    "ISO":       (["ISO 100", "ISO 200", "ISO 400", "ISO 800", "ISO 1600", "ISO 3200", "ISO 6400"],
                  lambda v: v),
    "快门速度":  (["1/4000s", "1/2000s", "1/1000s", "1/500s", "1/250s", "1/125s", "1/60s", "1s", "5s", "30s (长曝光)"],
                  lambda v: v.split()[0]),
    "特殊角度":  (["dutch angle (荷兰角/斜角)", "over the shoulder (过肩)",
                   "aerial drone shot (航拍无人机)", "pov shot (第一人称视角)",
                   "through glass (透过玻璃)", "reflection shot (镜像反射)"],
                  lambda v: v.split("(")[0].strip()),
    "镜头稳定":  (["handheld (手持晃动)", "steadicam (斯坦尼康稳定)",
                   "tripod (三脚架固定)", "dolly shot (推轨移动)",
                   "crane shot (摇臂升降)", "gimbal stabilized (电子稳定)"],
                  lambda v: v.split("(")[0].strip()),
    "胶片格式":  (["anamorphic 2.39:1 (变形镜头宽幕)", "spherical (球面标准)",
                   "IMAX 70mm (大画幅IMAX)", "Super 35mm (超35mm)",
                   "16mm film (16mm胶片)", "8mm vintage (8mm复古)"],
                  lambda v: v.split("(")[0].strip()),
    "构图方式":  (["rule of thirds (三分法)", "centered (居中)", "leading lines (引导线)",
                   "frame within frame (框中框)", "symmetrical (对称)",
                   "golden ratio (黄金比例)", "negative space (留白)"],
                  lambda v: v.split("(")[0].strip()),
    "景深":      (["shallow depth of field (浅景深)", "deep depth of field (深景深)",
                   "medium depth of field (中等景深)"],
                  lambda v: v.split("(")[0].strip()),
    "相机机型":  (["Sony A7IV", "Canon EOS R5", "Nikon Z9", "Fujifilm X-T5",
                   "Leica M11", "Hasselblad X2D", "Arri Alexa Mini",
                   "DJI Air 3 (无人机)", "GoPro Hero 12 (运动相机)"],
                  lambda v: f"shot on {v.split('(')[0].strip()}"),
    "打光风格":  (["natural light (自然光)", "golden hour (黄金时段)", "blue hour (蓝调时段)",
                   "Rembrandt lighting (伦勃朗光)", "rim lighting (轮廓光)",
                   "softbox lighting (柔光箱)", "hard light (硬光)", "backlight (逆光)"],
                  lambda v: v.split("(")[0].strip()),
    "色调风格":  (["teal and orange (青橙)", "warm tones (暖调)", "cool tones (冷调)",
                   "black and white (黑白)", "desaturated (低饱和)",
                   "vivid colors (高饱和)", "vintage (复古)"],
                  lambda v: v.split("(")[0].strip()),
    "画面比例":  (["16:9", "4:3", "1:1 (方形)", "2.39:1 (宽银幕)", "9:16 (竖屏)", "4:5"],
                  lambda v: f"aspect ratio {v.split()[0]}"),
    "品质":      (["4K", "8K", "photorealistic", "highly detailed", "sharp focus", "RAW photo"],
                  lambda v: v),
}

# 二次元模式基础参数
PARAMS_ANIME = {
    "构图视角":  (["standard anime shot (标准动画视角)",
                   "low angle anime (仰视构图)",
                   "top-down anime (俯视构图)",
                   "anime portrait (近距人物视角)",
                   "exaggerated wide angle (极大广角夸张视角)",
                   "dynamic diagonal composition (对角线动态构图)",
                   "symmetrical composition (对称构图)",
                   "over the shoulder anime (过肩构图)",
                   "frame within frame (框中框构图)",
                   "rule of thirds (三分法构图)",
                   "negative space composition (大留白构图)"],
                  lambda v: v.split("(")[0].strip()),
    "渲染风格":  (["cel shading (赛璐珞)", "anime key visual (动画关键帧风格)",
                   "watercolor illustration (水彩插画)", "thick paint (厚涂)",
                   "sketch style (素描)", "pixel art (像素风)",
                   "flat design (扁平设计)"],
                  lambda v: v.split("(")[0].strip()),
    "画风词":    (["Studio Ghibli style", "KyoAni style", "Makoto Shinkai style",
                   "Trigger style", "A-1 Pictures style", "Ufotable style",
                   "WIT Studio style", "MAPPA style", "Production I.G style",
                   "Gainax style", "Madhouse style", "Science SARU style",
                   "Tatsuki Fujimoto style", "J.C.Staff style", "CloverWorks style"],
                  lambda v: v),
    "动画打光":  (["anime sunlight (动画阳光)", "rim light with glow (发光轮廓光)",
                   "flat lighting (扁平光)", "dramatic shadow (戏剧阴影)",
                   "soft ambient light (柔和环境光)", "night scene lighting (夜景灯光)"],
                  lambda v: v.split("(")[0].strip()),
    "画面色调":  (["saturated vivid (高饱和鲜艳)", "pastel soft (粉彩柔和)",
                   "dark fantasy (暗黑奇幻)", "warm sunset (温暖日落)",
                   "cool moonlight (冷蓝月光)", "neon cyberpunk (霓虹赛博朋克)"],
                  lambda v: v.split("(")[0].strip()),
    "情绪氛围":  (["peaceful and gentle (温柔宁静)", "tense and dramatic (紧张震撼)",
                   "daily life (日常轻松)", "lonely melancholy (孤独忧郁)",
                   "epic and grand (史诗磅礴)", "mysterious (神秘)"],
                  lambda v: v.split("(")[0].strip()),
    "画面比例":  (["16:9", "4:3", "1:1 (方形)", "2.39:1 (宽银幕)", "9:16 (竖屏)"],
                  lambda v: f"aspect ratio {v.split()[0]}"),
    "品质":      (["anime illustration, 4K", "best quality, masterpiece",
                   "ultra detailed, official art", "highres, detailed background"],
                  lambda v: v),
}

# 滤镜积木词库  {类别: [(中文标签, 英文关键词), ...]}
FILTER_KEYWORDS = {
    "🎞 胶片滤镜": [
        ("柯达Portra400 / Kodak Portra 400",  "Kodak Portra 400"),
        ("富士Velvia50 / Fuji Velvia 50",      "Fuji Velvia 50"),
        ("伊尔福HP5 / Ilford HP5 Plus",        "Ilford HP5 Plus"),
        ("交叉冲洗 / cross-process",            "cross-process"),
        ("过期胶片 / expired film",             "expired film"),
        ("LOMO风格 / lomography",               "lomography"),
        ("柯达Ektachrome / Ektachrome",         "Ektachrome"),
        ("柯达Gold200 / Kodak Gold 200",        "Kodak Gold 200"),
        ("夜用胶片 / Cinestill 800T",           "Cinestill 800T"),
        ("黑白胶片 / black and white film",     "black and white film"),
    ],
    "🎨 色彩分级": [
        ("青橙色调 / teal and orange",          "teal and orange"),
        ("褪色胶片 / faded film",               "faded film"),
        ("日转夜 / day for night",              "day for night"),
        ("漂白旁路 / bleach bypass",            "bleach bypass"),
        ("分离调色 / split toning",             "split toning"),
        ("双色调 / duotone",                    "duotone"),
        ("橙色阴影 / orange shadow",            "orange shadow"),
        ("绿色薄雾 / green mist",               "green mist"),
        ("冷蓝调 / cold blue grade",            "cold blue grade"),
        ("暖棕调 / warm brown grade",           "warm brown grade"),
    ],
    "✨ 光线特效": [
        ("镜头光晕 / lens flare",               "lens flare"),
        ("丁达尔光 / god rays",                 "god rays"),
        ("焦外光斑 / bokeh balls",              "bokeh balls"),
        ("漏光 / light leak",                   "light leak"),
        ("变形镜头光晕 / anamorphic flare",     "anamorphic flare"),
        ("太阳眩光 / sun glare",                "sun glare"),
        ("焦散光 / caustic light",              "caustic light"),
        ("体积光 / volumetric light",           "volumetric light"),
        ("星芒 / starburst",                    "starburst"),
        ("边缘光 / rim light",                  "rim light"),
    ],
    "🖼 后期风格": [
        ("高动态范围 / HDR",                    "HDR"),
        ("多重曝光 / double exposure",          "double exposure"),
        ("暗角 / vignette",                     "vignette"),
        ("胶片颗粒 / film grain",               "film grain"),
        ("色差 / chromatic aberration",         "chromatic aberration"),
        ("长曝光模糊 / long exposure blur",     "long exposure blur"),
        ("运动模糊 / motion blur",              "motion blur"),
        ("移轴效果 / tilt-shift",               "tilt-shift"),
        ("故障艺术 / glitch art",               "glitch art"),
        ("像素化 / pixelation",                 "pixelation"),
    ],
    "🌫 氛围效果": [
        ("雾 / fog",                            "fog"),
        ("薄雾 / haze",                         "haze"),
        ("轻雾 / mist",                         "mist"),
        ("雨 / rain",                           "rain"),
        ("雪 / snow",                           "snow"),
        ("尘埃粒子 / dust particles",           "dust particles"),
        ("烟雾 / smoke",                        "smoke"),
        ("极光 / aurora",                       "aurora"),
        ("星空 / starry sky",                   "starry sky"),
        ("落叶 / falling leaves",               "falling leaves"),
    ],
    "📐 镜头特性": [
        ("桶形畸变 / barrel distortion",        "barrel distortion"),
        ("鱼眼 / fisheye",                      "fisheye"),
        ("微距细节 / macro detail",             "macro detail"),
        ("柔焦 / soft focus",                   "soft focus"),
        ("极致锐利 / pin sharp",                "pin sharp"),
        ("衍射光晕 / diffraction glow",         "diffraction glow"),
        ("超广角变形 / ultra-wide distortion",  "ultra-wide distortion"),
        ("长焦压缩 / telephoto compression",    "telephoto compression"),
        ("旋转焦外 / swirly bokeh",             "swirly bokeh"),
        ("猫眼焦外 / cat eye bokeh",            "cat eye bokeh"),
    ],
}

# 景别（0=超远景，6=超微距）
SHOT_SCALE = [
    ("extreme wide shot",  "超远景 — 宏大环境，人物极小"),
    ("wide shot",          "远景 — 人物全身可见"),
    ("medium shot",        "中景 — 腰部以上"),
    ("close-up",           "近景 — 脸部/胸口"),
    ("extreme close-up",   "特写 — 眼睛/嘴唇"),
    ("macro shot",         "微距 — 极近细节"),
    ("extreme macro",      "超微距 — 昆虫翅膀级细节"),
]

# 摄影机俯仰角（0=仰视极端，6=俯视极端）
CAMERA_ELEVATION = [
    ("worm's eye view, extreme low angle",  "虫视极端仰 — 完全仰视地面视角"),
    ("low angle shot",                       "低角仰拍 — 镜头低于主体向上"),
    ("slight low angle",                     "轻微仰拍 — 略低于平视"),
    ("eye level shot",                       "平视 — 与主体眼部同高"),
    ("slight high angle",                    "轻微俯拍 — 略高于平视"),
    ("high angle shot",                      "高角俯拍 — 镜头高于主体向下"),
    ("bird's eye view, overhead shot",       "鸟瞰/顶视 — 几乎垂直向下俯拍"),
]

# 主体方位角（0=正面，顺时针8方位）
SUBJECT_ANGLE = [
    ("front view, facing camera directly",   "正面 — 主体正面朝向镜头"),
    ("front-left three-quarter view",        "左前45° — 前四分之三侧面"),
    ("left side profile view",               "正左侧 — 完整左侧轮廓"),
    ("rear-left three-quarter view",         "左后45° — 后四分之三背侧"),
    ("back view, shot from behind",          "正背面 — 完整背影"),
    ("rear-right three-quarter view",        "右后45° — 后四分之三背侧"),
    ("right side profile view",              "正右侧 — 完整右侧轮廓"),
    ("front-right three-quarter view",       "右前45° — 前四分之三侧面"),
]

# 电影/实拍预设
PRESETS_REAL = {
    # ── 科幻/未来 ──
    "《银翼杀手2049》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/2.8", "ISO": "ISO 800",
        "快门速度": "1/60s", "构图方式": "leading lines (引导线)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "blue hour (蓝调时段)",
        "色调风格": "teal and orange (青橙)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "anamorphic lens flare, rain, neon reflections, cinematic, Roger Deakins cinematography",
    },
    "《星际穿越》": {
        "镜头焦距": "14mm (超广角)", "光圈": "f/11", "ISO": "ISO 100",
        "快门速度": "1/500s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "cool tones (冷调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "IMAX 70mm, dramatic sky, high contrast, cosmic atmosphere, Hoyte van Hoytema cinematography",
    },
    "《沙丘》": {
        "镜头焦距": "24mm (广角)", "光圈": "f/8", "ISO": "ISO 200",
        "快门速度": "1/1000s", "构图方式": "negative space (留白)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "golden hour (黄金时段)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "desert landscape, epic scale, sand dunes, Greig Fraser cinematography, IMAX",
    },
    "《黑客帝国》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/2.8", "ISO": "ISO 800",
        "快门速度": "1/60s", "构图方式": "leading lines (引导线)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "hard light (硬光)",
        "色调风格": "teal and orange (青橙)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "dutch angle, green tint, bullet time blur, rain, neon, Bill Pope cinematography",
    },
    "《2001太空漫游》": {
        "镜头焦距": "14mm (超广角)", "光圈": "f/11", "ISO": "ISO 100",
        "快门速度": "1/250s", "构图方式": "symmetrical (对称)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "cool tones (冷调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Stanley Kubrick visual style, one-point perspective, sterile white environment, Geoffrey Unsworth cinematography",
    },
    # ── 战争/历史 ──
    "《拯救大兵瑞恩》": {
        "镜头焦距": "24mm (广角)", "光圈": "f/5.6", "ISO": "ISO 400",
        "快门速度": "1/500s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "desaturated (低饱和)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "handheld camera, gritty texture, Janusz Kaminski cinematography, bleach bypass, overcast diffused light",
    },
    "《1917》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/2.8", "ISO": "ISO 1600",
        "快门速度": "1/60s", "构图方式": "leading lines (引导线)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "desaturated (低饱和)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "one-shot continuous take style, trench environment, Roger Deakins cinematography, golden hour transition",
    },
    "《敦刻尔克》": {
        "镜头焦距": "14mm (超广角)", "光圈": "f/8", "ISO": "ISO 400",
        "快门速度": "1/1000s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "cool tones (冷调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "IMAX 70mm, beach and sea environment, handheld camera, gritty texture, Hoyte van Hoytema cinematography",
    },
    "《七武士》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/5.6", "ISO": "ISO 400",
        "快门速度": "1/250s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "black and white (黑白)", "画面比例": "4:3", "品质": "highly detailed",
        "_extra": "Akira Kurosawa visual style, rain, mud texture, Asakazu Nakai cinematography, telephoto compression",
    },
    # ── 剧情/人文 ──
    "《教父》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/2.8", "ISO": "ISO 400",
        "快门速度": "1/60s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "Rembrandt lighting (伦勃朗光)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Gordon Willis cinematography, deep shadow, low key, chiaroscuro, 1970s film look",
    },
    "《肖申克的救赎》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/4", "ISO": "ISO 200",
        "快门速度": "1/250s", "构图方式": "leading lines (引导线)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Roger Deakins cinematography, dramatic sky, warm golden light, stone architectural environment",
    },
    "《寄生虫》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/4", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "symmetrical (对称)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "desaturated (低饱和)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Hong Kyung-pyo cinematography, staircase composition, stark architectural contrast, high-end interior vs cramped space",
    },
    "《月光男孩》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/1.8", "ISO": "ISO 800",
        "快门速度": "1/60s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "blue hour (蓝调时段)",
        "色调风格": "teal and orange (青橙)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "James Laxton cinematography, moonlight, blue teal color grading, intimate handheld",
    },
    "《请回答1988》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/2.8", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Sony A7IV", "打光风格": "golden hour (黄金时段)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "highly detailed",
        "_extra": "1980s period setting, warm vintage color grade, narrow alley environment, soft film grain",
    },
    # ── 风格化 ──
    "《布达佩斯大饭店》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/5.6", "ISO": "ISO 200",
        "快门速度": "1/250s", "构图方式": "symmetrical (对称)", "景深": "deep depth of field (深景深)",
        "相机机型": "Fujifilm X-T5", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "4:3", "品质": "highly detailed",
        "_extra": "Wes Anderson visual style, pastel color palette, flat graphic composition, Robert Yeoman cinematography",
    },
    "《爱乐之城》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/2.8", "ISO": "ISO 400",
        "快门速度": "1/60s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "golden hour (黄金时段)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Linus Sandgren cinematography, magic hour lighting, vibrant color palette, open-air urban backdrop",
    },
    "《老男孩》": {
        "镜头焦距": "24mm (广角)", "光圈": "f/2.8", "ISO": "ISO 1600",
        "快门速度": "1/60s", "构图方式": "leading lines (引导线)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Sony A7IV", "打光风格": "hard light (硬光)",
        "色调风格": "desaturated (低饱和)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "dutch angle, Park Chan-wook visual style, long corridor environment, dark atmosphere",
    },
    "《疯狂的麦克斯：狂暴之路》": {
        "镜头焦距": "24mm (广角)", "光圈": "f/4", "ISO": "ISO 200",
        "快门速度": "1/2000s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "golden hour (黄金时段)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "John Seale cinematography, desert landscape, dust haze, high-speed motion blur, bleached wasteland colors",
    },
    "《利刃出鞘》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/4", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "frame within frame (框中框)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Steve Yedlin cinematography, manor house interior, warm ambient lighting, rich decorative environment",
    },
    "《奥本海默》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/2.8", "ISO": "ISO 800",
        "快门速度": "1/60s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "desaturated (低饱和)", "画面比例": "2.39:1 (宽银幕)", "品质": "photorealistic",
        "_extra": "Hoyte van Hoytema cinematography, IMAX 70mm, desaturated color grading, industrial New Mexico landscape, intense extreme close-up portrait",
    },
    # ── 美食纪录片 / 美食电影 ──
    "《孤独的美食家》": {
        "镜头焦距": "100mm (微距)", "光圈": "f/2.8", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Sony A7IV", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "photorealistic",
        "_extra": "close-up food photography, steam wisps, warm restaurant interior lighting, cozy izakaya atmosphere",
    },
    "《舌尖上的中国》": {
        "镜头焦距": "100mm (微距)", "光圈": "f/4", "ISO": "ISO 200",
        "快门速度": "1/125s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "photorealistic",
        "_extra": "close-up ingredient texture, handcraft cooking process, documentary cinematography, warm earthy tones, natural window light",
    },
    "《深夜食堂》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/2.8", "ISO": "ISO 1600",
        "快门速度": "1/60s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Sony A7IV", "打光风格": "Rembrandt lighting (伦勃朗光)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "highly detailed",
        "_extra": "night alley diner environment, izakaya interior, late-night dim warm lighting, steam detail",
    },
    "《朱莉与朱莉娅》": {
        "镜头焦距": "50mm (标准)", "光圈": "f/2.8", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "rule of thirds (三分法)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Canon EOS R5", "打光风格": "softbox lighting (柔光箱)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "photorealistic",
        "_extra": "French kitchen environment, 1950s period interior decor, warm color grade, soft overhead lighting",
    },
    "《寿司之神》": {
        "镜头焦距": "100mm (微距)", "光圈": "f/2.8", "ISO": "ISO 200",
        "快门速度": "1/250s", "构图方式": "centered (居中)", "景深": "shallow depth of field (浅景深)",
        "相机机型": "Canon EOS R5", "打光风格": "softbox lighting (柔光箱)",
        "色调风格": "desaturated (低饱和)", "画面比例": "16:9", "品质": "photorealistic",
        "_extra": "extreme close-up food macro, minimalist plating, precision craftsmanship detail, clean white counter, warm spotlight",
    },
    "《饮食男女》": {
        "镜头焦距": "35mm (标准广角)", "光圈": "f/4", "ISO": "ISO 400",
        "快门速度": "1/125s", "构图方式": "rule of thirds (三分法)", "景深": "deep depth of field (深景深)",
        "相机机型": "Arri Alexa Mini", "打光风格": "natural light (自然光)",
        "色调风格": "warm tones (暖调)", "画面比例": "16:9", "品质": "photorealistic",
        "_extra": "Ang Lee cinematography style, colorful dish arrangement, steam and cooking atmosphere, warm natural light, rich color palette",
    },
}

# 动画/二次元预设
PRESETS_ANIME = {
    # ── 吉卜力系 ──
    "《千与千寻》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Studio Ghibli style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "mysterious (神秘)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "Hayao Miyazaki visual style, highly detailed architecture, lush environment painting, warm color palette, dense layered background",
    },
    "《幽灵公主》": {
        "构图视角": "exaggerated wide angle (极大广角夸张视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Studio Ghibli style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "epic and grand (史诗磅礴)",
        "画面比例": "16:9", "品质": "ultra detailed, official art",
        "_extra": "Hayao Miyazaki visual style, dense ancient forest environment, mist and diffused light, rich foliage texture",
    },
    # ── 新海诚系 ──
    "《你的名字》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Makoto Shinkai style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "twilight sky, photorealistic cloud rendering, comet trail, golden volumetric light, CoMix Wave Films visual style",
    },
    "《天气之子》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Makoto Shinkai style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "epic and grand (史诗磅礴)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "heavy rain visual, sunshine hole breaking through clouds, dramatic sky layering, god rays, urban rooftop environment",
    },
    # ── 京阿尼系 ──
    "《紫罗兰永恒花园》": {
        "构图视角": "anime portrait (近距人物视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "KyoAni style",
        "动画打光": "soft ambient light (柔和环境光)",
        "画面色调": "pastel soft (粉彩柔和)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "16:9", "品质": "anime illustration, 4K",
        "_extra": "KyoAni visual quality, European period architecture, soft diffused lighting, delicate fabric texture, pastel floral environment",
    },
    "《孤独摇滚》": {
        "构图视角": "anime portrait (近距人物视角)",
        "渲染风格": "cel shading (赛璐珞)",
        "画风词": "CloverWorks style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "neon cyberpunk (霓虹赛博朋克)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "stage spotlights, neon concert lighting, hard shadow contrast, bokeh lens flare, performance venue atmosphere",
    },
    # ── 战斗/热血 ──
    "《进击的巨人》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "WIT Studio style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "ultra detailed, official art",
        "_extra": "dark overcast sky, massive scale contrast, rough stone architecture, dynamic motion lines, gritty atmospheric haze",
    },
    "《鬼灭之刃》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Ufotable style",
        "动画打光": "rim light with glow (发光轮廓光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "best quality, masterpiece",
        "_extra": "Ufotable composite rendering style, luminous particle effects, fluid motion blur, vivid elemental color contrast, Taisho-era environment textures",
    },
    "《咒术回战》": {
        "构图视角": "exaggerated wide angle (极大广角夸张视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "MAPPA style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "ultra detailed, official art",
        "_extra": "MAPPA high-contrast rendering, dark energy visual effect, dynamic diagonal composition, gritty urban environment, heavy shadow",
    },
    # ── 科幻/赛博 ──
    "《攻壳机动队》": {
        "构图视角": "top-down anime (俯视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Production I.G style",
        "动画打光": "night scene lighting (夜景灯光)",
        "画面色调": "cool moonlight (冷蓝月光)",
        "情绪氛围": "mysterious (神秘)",
        "画面比例": "16:9", "品质": "ultra detailed, official art",
        "_extra": "Mamoru Oshii visual style, rainy cyberpunk cityscape, neon reflection on wet pavement, cool blue tone, dense urban skyline",
    },
    "《EVA》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "cel shading (赛璐珞)",
        "画风词": "Gainax style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "4:3", "品质": "ultra detailed, official art",
        "_extra": "Hideaki Anno visual style, stark industrial architecture, harsh fluorescent interior light, desaturated concrete environment, heavy shadow contrast",
    },
    # ── 治愈/日常 ──
    "《葬送的芙莉莲》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Madhouse style",
        "动画打光": "soft ambient light (柔和环境光)",
        "画面色调": "pastel soft (粉彩柔和)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "vast fantasy landscape, wildflower meadow, soft overcast diffused light, long road perspective, pastel natural color palette",
    },
    "《京阿尼日常》": {
        "构图视角": "anime portrait (近距人物视角)",
        "渲染风格": "cel shading (赛璐珞)",
        "画风词": "KyoAni style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "warm sunset (温暖日落)",
        "情绪氛围": "daily life (日常轻松)",
        "画面比例": "16:9", "品质": "anime illustration, 4K",
        "_extra": "KyoAni quality rendering, soft sunlight through window, cherry blossom bokeh, warm golden color grading, delicate line work",
    },
    # ── 艺术实验 ──
    "《蓦然回首》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "watercolor illustration (水彩插画)",
        "画风词": "Tatsuki Fujimoto style",
        "动画打光": "soft ambient light (柔和环境光)",
        "画面色调": "pastel soft (粉彩柔和)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "4:3", "品质": "best quality, masterpiece",
        "_extra": "Tatsuki Fujimoto illustration style, loose brushwork, soft watercolor wash, rural landscape, rain on window texture",
    },
    "《犬王》": {
        "构图视角": "exaggerated wide angle (极大广角夸张视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Science SARU style",
        "动画打光": "rim light with glow (发光轮廓光)",
        "画面色调": "neon cyberpunk (霓虹赛博朋克)",
        "情绪氛围": "epic and grand (史诗磅礴)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "ultra detailed, official art",
        "_extra": "Masaaki Yuasa fluid animation style, psychedelic color burst, distorted perspective, stage performance lighting, bold flat color",
    },
    # ── Fate 系 ──
    "《Fate/Zero》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Ufotable style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "16:9", "品质": "ultra detailed, official art",
        "_extra": "Ufotable cinematic lighting, rain and wet environment, dark night atmosphere, cold color grading, heavy shadow contrast",
    },
    "《Fate/stay night UBW》": {
        "构图视角": "exaggerated wide angle (极大广角夸张视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Ufotable style",
        "动画打光": "rim light with glow (发光轮廓光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "epic and grand (史诗磅礴)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "best quality, masterpiece",
        "_extra": "Ufotable composite rendering, golden energy particle burst, swords-in-sky visual, warm backlight glow, dynamic wide composition",
    },
    "《Fate/Heaven's Feel》": {
        "构图视角": "anime portrait (近距人物视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Ufotable style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "dark fantasy (暗黑奇幻)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "ultra detailed, official art",
        "_extra": "Ufotable dark rendering, deep shadow, corrupted black texture, cold desaturated palette, heavy vignette",
    },
    # ── 美食动画 ──
    "《食戟之灵》": {
        "构图视角": "exaggerated wide angle (极大广角夸张视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "J.C.Staff style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "close-up steaming dish, vibrant food color, dramatic overhead lighting, dynamic plate presentation, J.C.Staff visual style",
    },
    "《料理鼠王》(动画)": {
        "构图视角": "top-down anime (俯视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "动画打光": "soft ambient light (柔和环境光)",
        "画面色调": "warm sunset (温暖日落)",
        "情绪氛围": "peaceful and gentle (温柔宁静)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "best quality, masterpiece",
        "_extra": "Pixar 3D rendering aesthetic, French kitchen environment, warm incandescent interior light, Paris rooftop view, rich food color",
    },
    "《迷宫饭》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Trigger style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "warm sunset (温暖日落)",
        "情绪氛围": "daily life (日常轻松)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "Trigger visual style, warm campfire lighting, dungeon stone environment, rich food color palette, cozy interior atmosphere",
    },
    # ── 旧有预设保留 ──
    "《赛博朋克动画》": {
        "构图视角": "top-down anime (俯视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Trigger style",
        "动画打光": "night scene lighting (夜景灯光)",
        "画面色调": "neon cyberpunk (霓虹赛博朋克)",
        "情绪氛围": "mysterious (神秘)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "ultra detailed, official art",
        "_extra": "neon signs, rain puddle reflections, futuristic city skyline, cold blue and pink color contrast",
    },
    "《战斗场景》": {
        "构图视角": "low angle anime (仰视构图)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Ufotable style",
        "动画打光": "dramatic shadow (戏剧阴影)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "2.39:1 (宽银幕)", "品质": "best quality, masterpiece",
        "_extra": "motion blur, dynamic speed lines, particle energy effect, high contrast rim lighting",
    },
    "《押井守风格》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "cel shading (赛璐珞)",
        "画风词": "Production I.G style",
        "动画打光": "night scene lighting (夜景灯光)",
        "画面色调": "cool moonlight (冷蓝月光)",
        "情绪氛围": "mysterious (神秘)",
        "画面比例": "16:9", "品质": "ultra detailed, official art",
        "_extra": "Mamoru Oshii visual style, rain reflection on wet street, dystopian architecture, cold blue atmosphere, deep shadow",
    },
    "《新海诚风格》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "anime key visual (动画关键帧风格)",
        "画风词": "Makoto Shinkai style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "lonely melancholy (孤独忧郁)",
        "画面比例": "16:9", "品质": "best quality, masterpiece",
        "_extra": "god rays, photorealistic cloud detail, beautiful sky gradient, CoMix Wave Films visual style",
    },
    "《日常治愈》": {
        "构图视角": "standard anime shot (标准动画视角)",
        "渲染风格": "watercolor illustration (水彩插画)",
        "画风词": "KyoAni style",
        "动画打光": "anime sunlight (动画阳光)",
        "画面色调": "warm sunset (温暖日落)",
        "情绪氛围": "daily life (日常轻松)",
        "画面比例": "16:9", "品质": "anime illustration, 4K",
        "_extra": "school building background, cherry blossom bokeh, soft afternoon light",
    },
    "《京阿尼人像》": {
        "构图视角": "anime portrait (近距人物视角)",
        "渲染风格": "cel shading (赛璐珞)",
        "画风词": "KyoAni style",
        "动画打光": "soft ambient light (柔和环境光)",
        "画面色调": "pastel soft (粉彩柔和)",
        "情绪氛围": "peaceful and gentle (温柔宁静)",
        "画面比例": "16:9", "品质": "anime illustration, 4K",
        "_extra": "KyoAni detailed rendering, soft shadow gradient, delicate highlight on hair, diffused background light",
    },
    "《恶童》(松本大洋)": {
        "构图视角": "dynamic diagonal composition (对角线动态构图)",
        "渲染风格": "thick paint (厚涂)",
        "画风词": "Science SARU style",
        "动画打光": "flat lighting (扁平光)",
        "画面色调": "saturated vivid (高饱和鲜艳)",
        "情绪氛围": "tense and dramatic (紧张震撼)",
        "画面比例": "16:9", "品质": "ultra detailed, official art",
        "_extra": "Matsumoto Taiyou illustration style, graffiti-textured background, bold ink linework, flat saturated color blocking, Masaaki Yuasa animation direction",
    },
}

# ── 主体场景快速词块 ─────────────────────────────────────────────
SUBJECT_CHIPS_REAL = [
    ("a young woman", "年轻女性"),
    ("an elderly man", "老年男性"),
    ("a child", "孩童"),
    ("a couple", "一对情侣"),
    ("a crowd", "人群"),
    ("a lone figure", "孤独身影"),
    ("a portrait subject", "人像主体"),
    ("a street performer", "街头表演者"),
]
SUBJECT_CHIPS_ANIME = [
    ("original girl character", "原创少女"),
    ("anime boy", "二次元少年"),
    ("magical girl", "魔法少女"),
    ("mecha pilot", "机甲驾驶员"),
    ("isekai hero", "异世界勇者"),
    ("cat-ear girl", "猫耳少女"),
    ("cyberpunk girl", "赛博朋克少女"),
    ("vampire character", "吸血鬼角色"),
]
ENVIRONMENT_CHIPS_REAL = [
    ("urban street", "城市街道"),
    ("forest", "森林"),
    ("desert", "沙漠"),
    ("mountain peak", "山顶"),
    ("ocean shore", "海岸"),
    ("rooftop", "屋顶"),
    ("underground subway", "地下地铁"),
    ("old industrial district", "旧工业区"),
]
ENVIRONMENT_CHIPS_ANIME = [
    ("cherry blossom school campus", "樱花校园"),
    ("fantasy forest", "异世界森林"),
    ("cyberpunk city", "赛博都市"),
    ("magic castle", "魔法城堡"),
    ("starry night meadow", "星空下草原"),
    ("ancient temple ruins", "古代神殿"),
    ("post-apocalyptic wasteland", "废土末世"),
    ("underwater world", "水下世界"),
]

# ── 风格词块 ─────────────────────────────────────────────────────
STYLE_REAL = [
    ("photorealistic", "写实摄影"),
    ("cinematic", "电影感"),
    ("documentary photography", "纪录片"),
    ("fine art photography", "艺术摄影"),
    ("editorial photography", "时尚杂志"),
    ("street photography", "街头摄影"),
    ("architectural photography", "建筑摄影"),
    ("wildlife photography", "野生动物摄影"),
]
STYLE_ANIME = [
    ("Studio Ghibli style", "吉卜力风"),
    ("Makoto Shinkai style", "新海诚风"),
    ("cel shading", "赛璐璐"),
    ("watercolor illustration", "水彩插画"),
    ("pixel art", "像素风"),
    ("thick paint", "厚涂"),
    ("flat design", "扁平设计"),
    ("retro anime 80s", "复古80年代风"),
]

# ── 情绪词块 ─────────────────────────────────────────────────────
MOOD_REAL = [
    ("dramatic", "戏剧性"),
    ("serene", "宁静"),
    ("melancholic", "忧郁"),
    ("energetic", "充满活力"),
    ("mysterious", "神秘"),
    ("romantic", "浪漫"),
    ("tense", "紧张"),
    ("nostalgic", "怀旧"),
]
MOOD_ANIME = [
    ("healing and gentle", "治愈系"),
    ("chuunibyou dramatic", "中二病"),
    ("mono no aware", "物哀"),
    ("intense battle spirit", "热血"),
    ("everyday slice of life", "日常"),
    ("dark and brooding", "暗黑"),
    ("whimsical fantasy", "奇幻"),
    ("bittersweet", "苦中带甜"),
]

# ── 动作/动态（实拍+动画共用） ────────────────────────────────────
MOTION_OPTIONS = [
    "（不指定）",
    "walking slowly",
    "running at full speed",
    "jumping mid-air",
    "standing still, slight breeze",
    "dancing gracefully",
    "reaching out hand",
    "looking back over shoulder",
    "crouching low",
    "falling",
    "floating",
    "sitting cross-legged",
    "kneeling",
    "lying down",
    "looking up at sky",
    "arms raised",
]

# ── 细节/质感词块 ────────────────────────────────────────────────
TEXTURE_REAL = [
    ("skin pores visible", "皮肤毛孔"),
    ("fabric weave detail", "织物纹理"),
    ("metallic sheen", "金属光泽"),
    ("wet surface", "湿润表面"),
    ("rough stone texture", "粗糙石质"),
    ("glass reflections", "玻璃反射"),
    ("wood grain", "木纹"),
    ("leather texture", "皮革质感"),
]
TEXTURE_ANIME = [
    ("cel shading outline", "赛璐璐描边"),
    ("flat color blocks", "平涂色块"),
    ("gradient hair shading", "渐变发丝"),
    ("sparkle effect", "闪光特效"),
    ("soft shadow rendering", "柔和阴影"),
    ("glowing aura", "发光光晕"),
    ("detailed eye catchlight", "眼睛高光"),
    ("screen tone pattern", "网点纸"),
]

# ── 色彩补充词块 ─────────────────────────────────────────────────
COLOR_SUPPLEMENT_REAL = [
    ("vibrant saturated colors", "高饱和"),
    ("muted desaturated palette", "低饱和"),
    ("monochromatic", "单色调"),
    ("complementary color contrast", "互补色对比"),
    ("analogous warm tones", "暖色系"),
    ("cool color palette", "冷色系"),
]
COLOR_SUPPLEMENT_ANIME = [
    ("pastel color palette", "马卡龙色"),
    ("neon cyberpunk colors", "霓虹赛博"),
    ("sakura pink tones", "樱花粉调"),
    ("dark gothic palette", "暗黑哥特"),
    ("golden sunset gradient", "黄昏渐变"),
    ("ocean blue tones", "海洋蓝调"),
]

# ── 渲染引擎 / 输出比例 ──────────────────────────────────────────
RENDER_ENGINES = [
    "（不指定）", "Unreal Engine 5", "Octane Render", "Blender Cycles",
    "V-Ray", "Arnold", "Redshift", "KeyShot",
]
OUTPUT_RATIOS = [
    "（不指定）", "1:1", "4:3", "16:9", "9:16", "2:3", "3:2", "2.39:1",
]

# ── 时间/天气快速词块 ────────────────────────────────────────────
WEATHER_CHIPS_REAL = [
    ("dawn", "黎明"),
    ("golden hour", "黄金时段"),
    ("midday", "正午"),
    ("dusk", "黄昏"),
    ("midnight", "午夜"),
    ("clear sky", "晴空"),
    ("overcast", "阴天"),
    ("foggy", "雾天"),
    ("rainy", "雨天"),
    ("snowy", "雪天"),
    ("stormy", "暴风雨"),
]
WEATHER_CHIPS_ANIME = [
    ("sunny daylight", "晴天阳光"),
    ("sunset golden light", "黄昏夕照"),
    ("full moon night", "夜晚满月"),
    ("overcast rain", "阴雨天"),
    ("snowfall", "雪天"),
    ("mysterious mist", "神秘薄雾"),
    ("lightning storm", "雷电交加"),
]

# ── 人数/关系快速词块 ────────────────────────────────────────────
SUBJECT_COUNT_REAL = [
    ("solo", "单人"),
    ("duo", "两人"),
    ("small group (3-5)", "小群体"),
    ("crowd", "人群"),
    ("no humans", "无人"),
]
SUBJECT_COUNT_ANIME = [
    ("solo character", "独处"),
    ("two characters", "双人"),
    ("multiple characters", "多角色"),
    ("no characters, scenery only", "无人场景"),
]

# ── 美学流派词块 ─────────────────────────────────────────────────
AESTHETIC_REAL = [
    ("film noir", "黑色电影"),
    ("cyberpunk", "赛博朋克"),
    ("steampunk", "蒸汽朋克"),
    ("baroque", "巴洛克"),
    ("minimalist", "极简主义"),
    ("surrealism", "超现实主义"),
    ("impressionism", "印象派"),
    ("pop art", "波普艺术"),
]
AESTHETIC_ANIME = [
    ("steampunk", "蒸汽朋克"),
    ("retro 80s anime", "复古80年代"),
    ("wuxia xianxia", "武侠仙侠"),
    ("lovecraftian horror", "克苏鲁"),
    ("post-apocalyptic wasteland", "末世废土"),
    ("dreamy fairy tale", "梦幻童话"),
    ("dark fantasy", "黑暗奇幻"),
    ("hard sci-fi mecha", "机甲硬科幻"),
]

# ── 质量词块 ─────────────────────────────────────────────────────
QUALITY_CHIPS_REAL = [
    ("masterpiece", "大师之作"),
    ("best quality", "最佳质量"),
    ("highly detailed", "超高细节"),
    ("sharp focus", "锐利对焦"),
    ("photorealistic", "照片真实感"),
    ("RAW photo", "RAW格式"),
    ("8K", "8K分辨率"),
    ("award winning photography", "获奖摄影"),
]
QUALITY_CHIPS_ANIME = [
    ("masterpiece", "大师之作"),
    ("best quality", "最佳质量"),
    ("ultra detailed", "超高细节"),
    ("official art", "官方插画"),
    ("anime illustration", "动画插画"),
    ("highres", "高分辨率"),
    ("beautiful detailed eyes", "精美眼睛"),
    ("delicate linework", "精细线稿"),
]

# ── 负面提示词预设 ────────────────────────────────────────────────
NEG_PRESETS = {
    "通用": "bad anatomy, bad hands, extra fingers, missing fingers, malformed, blurry, lowres, watermark, text, signature, cropped, worst quality, low quality, normal quality, jpeg artifacts, ugly, duplicate",
    "实拍专用": "(cartoon, anime, illustration, drawing, painting:1.4), oversaturated, unrealistic skin, plastic, CGI, 3d render",
    "动画专用": "(photorealistic, 3d, CGI, realistic skin:1.4), bad proportions, stiff pose, blurry lines, off-model, inconsistent style",
}

# ── 负面提示词自然中文映射 ─────────────────────────────────────────
NEGATIVE_ZH_MAP = {
    # 人体/解剖
    "bad anatomy": "避免错误人体结构",
    "bad hands": "避免手部畸形",
    "extra fingers": "避免多余手指",
    "missing fingers": "避免手指缺失",
    "extra limbs": "避免多余肢体",
    "missing limbs": "避免肢体缺失",
    "deformed": "避免形体变形",
    "malformed": "避免形态异常",
    "mutated": "避免异变形态",
    "disfigured": "避免毁容效果",
    "fused fingers": "避免手指粘连",
    "too many fingers": "避免手指过多",
    "long neck": "避免颈部过长",
    "bad proportions": "避免比例失调",
    "asymmetric face": "避免面部不对称",
    # 画质/技术
    "blurry": "避免模糊",
    "lowres": "避免低分辨率",
    "low quality": "避免低质量",
    "worst quality": "避免最低质量",
    "normal quality": "避免普通质量",
    "jpeg artifacts": "避免JPEG压缩噪点",
    "compression artifacts": "避免压缩失真",
    "noisy": "避免画面噪点",
    "grainy": "避免颗粒感过重",
    "pixelated": "避免像素化",
    "oversaturated": "避免过度饱和",
    "overexposed": "避免过曝",
    "underexposed": "避免欠曝",
    "out of focus": "避免失焦",
    # 内容/标记
    "watermark": "避免水印",
    "text": "避免文字叠加",
    "signature": "避免签名",
    "username": "避免用户名",
    "logo": "避免标志水印",
    "cropped": "避免画面被裁切",
    "frame": "避免边框",
    "border": "避免边框",
    "duplicate": "避免重复元素",
    "ugly": "避免丑陋效果",
    "amateur": "避免业余感",
    # 风格排除（实拍）
    "cartoon": "压制卡通感",
    "anime": "压制动画感",
    "illustration": "压制插画感",
    "drawing": "压制手绘感",
    "painting": "压制绘画感",
    "unrealistic skin": "避免不真实肤质",
    "plastic": "避免塑料质感",
    "cgi": "压制CGI感",
    "3d render": "压制三维渲染感",
    "3d": "压制三维感",
    # 风格排除（动画）
    "photorealistic": "压制写实感",
    "realistic skin": "压制真实肤感",
    "stiff pose": "避免僵硬姿态",
    "blurry lines": "避免线条模糊",
    "off-model": "避免角色走形",
    "inconsistent style": "避免风格不统一",
    # 情绪/内容
    "violence": "避免暴力内容",
    "nsfw": "避免不适内容",
    "gore": "避免血腥画面",
}

# ── 二次元风格提炼器预设库 ───────────────────────────────────────────
ANIME_STYLE_EXTRACTOR_PRESETS = [
    {
        "name": "吉卜力 Studio Ghibli",
        "category": "治愈系",
        "linework": "soft rounded outlines, hand-painted feel",
        "shading": "watercolor-like soft shading, gentle color transitions",
        "lighting": "warm natural sunlight, dappled light through leaves",
        "palette": "warm earthy greens, sky blues, golden yellows",
        "composition": "wide landscape establishing shots, small figure in grand nature",
        "mood": "peaceful wonder, nostalgic warmth",
        "motion": "gentle swaying, slow walk through nature",
        "background_detail": "highly detailed environment painting, lush vegetation, architectural texture",
        "keywords": ["Studio Ghibli style", "watercolor illustration", "soft warm lighting", "lush detailed background", "hand-painted texture"],
        "zh_summary": "吉卜力风：水彩质感、自然暖光、大自然景观、温暖怀旧氛围",
        "zh_details": {
            "linework": "柔和圆润的轮廓线，手绘水彩质感",
            "shading": "水彩式柔和明暗过渡，颜色轻盈通透",
            "lighting": "温暖自然阳光，树叶间的斑驳光影",
            "palette": "大地暖绿、天空蓝、金黄色调",
            "composition": "宽阔全景建立镜头，渺小人物立于壮阔自然中",
            "mood": "宁静的惊奇感，温暖怀旧情绪",
            "motion": "轻柔摇曳，在自然中缓步而行",
        },
    },
    {
        "name": "新海诚 Makoto Shinkai",
        "category": "唯美系",
        "linework": "clean detailed outlines, photorealistic backgrounds",
        "shading": "high-contrast cel shading on characters, photorealistic environment",
        "lighting": "god rays, golden volumetric light, dramatic sky gradients",
        "palette": "saturated vivid blues and oranges, twilight gradients, glowing whites",
        "composition": "character silhouette against dramatic sky, wide sky shots",
        "mood": "bittersweet longing, lonely melancholy, hopeful longing",
        "motion": "looking up at sky, hair blown by wind",
        "background_detail": "photorealistic cloud rendering, lens flare, urban architecture",
        "keywords": ["Makoto Shinkai style", "god rays", "photorealistic clouds", "saturated sky gradient", "bokeh lens flare"],
        "zh_summary": "新海诚风：高饱和天空、丁达尔光、写实背景、孤独唯美氛围",
        "zh_details": {
            "linework": "干净细腻的轮廓线，背景写实超精细",
            "shading": "角色高对比赛璐璐，背景写实渲染",
            "lighting": "丁达尔光、金色体积光、戏剧性天空渐变",
            "palette": "高饱和蓝橙撞色，黄昏渐变，发光白色",
            "composition": "人物剪影映衬戏剧性天空，宽幅天空镜头",
            "mood": "苦涩的思念，孤独忧郁，充满希望的渴望",
            "motion": "仰望天空，发丝被风吹动",
        },
    },
    {
        "name": "京都动画 KyoAni",
        "category": "日常系",
        "linework": "delicate fine linework, clean smooth contours",
        "shading": "soft gradient cel shading, delicate highlight on hair",
        "lighting": "soft diffused ambient light, warm sunlight through window",
        "palette": "pastel soft colors, warm golden tones, gentle pink accents",
        "composition": "character portrait close-up, everyday interior settings",
        "mood": "warm daily life, gentle emotion, delicate character expression",
        "motion": "sitting quietly, looking out window, subtle hair movement",
        "background_detail": "soft focus background bokeh, interior detail, cherry blossom",
        "keywords": ["KyoAni style", "cel shading", "soft ambient light", "delicate linework", "pastel soft"],
        "zh_summary": "京阿尼风：精细线稿、柔和渐变光、日常温柔氛围",
        "zh_details": {
            "linework": "纤细精密的描线，干净顺滑的轮廓",
            "shading": "柔和渐变赛璐璐，发丝高光精致",
            "lighting": "柔和漫射环境光，窗透暖阳",
            "palette": "粉彩柔色，暖金色调，淡粉色点缀",
            "composition": "人物近景特写，日常室内场景",
            "mood": "温暖日常，细腻情感，人物表情娇柔",
            "motion": "静坐望窗，发丝微动",
        },
    },
    {
        "name": "扳机社 Trigger",
        "category": "热血系",
        "linework": "bold thick outlines, exaggerated line weight variation",
        "shading": "high contrast flat cel shading, dramatic shadow shapes",
        "lighting": "dramatic rim lighting, high contrast hard light",
        "palette": "highly saturated vivid colors, bold color blocking",
        "composition": "dynamic diagonal composition, extreme perspective angles",
        "mood": "intense energy, over-the-top dramatic, passionate",
        "motion": "explosive action pose, mid-air jump, power stance",
        "background_detail": "speed lines, abstract energy patterns, bold graphic elements",
        "keywords": ["Trigger style", "cel shading", "dramatic shadow", "saturated vivid", "dynamic diagonal composition"],
        "zh_summary": "扳机社风：粗犷描边、高对比赛璐璐、极度夸张动感构图",
        "zh_details": {
            "linework": "粗犷厚重的描边，线条粗细变化夸张",
            "shading": "高对比平涂赛璐璐，阴影形状戏剧化",
            "lighting": "戏剧性轮廓光，高对比硬光",
            "palette": "极高饱和鲜艳色，粗犷色块对比",
            "composition": "对角线动感构图，极端透视角度",
            "mood": "爆发性能量，极度夸张热血，激情澎湃",
            "motion": "爆发性动作姿势，空中跳跃，战斗架势",
        },
    },
    {
        "name": "Ufotable 影院级",
        "category": "战斗系",
        "linework": "smooth precise outlines, CG-composite quality",
        "shading": "cinematic composite shading, luminous particle effects",
        "lighting": "rim light with glow, golden energy backlight, dramatic particle burst",
        "palette": "vibrant energy colors contrasting with dark backgrounds",
        "composition": "wide cinematic framing, low angle looking up at character",
        "mood": "epic battle intensity, awe-inspiring power",
        "motion": "dynamic mid-action, energy release, flowing cloth",
        "background_detail": "particle effects, elemental visual effects, cinematic environment detail",
        "keywords": ["Ufotable style", "rim light with glow", "luminous particle effects", "cinematic composite", "dark fantasy"],
        "zh_summary": "Ufotable风：影院级合成、发光粒子特效、史诗战斗氛围",
        "zh_details": {
            "linework": "流畅精准的轮廓线，CG合成级别品质",
            "shading": "电影级合成明暗，发光粒子特效",
            "lighting": "发光轮廓光，金色能量逆光，戏剧性粒子爆发",
            "palette": "鲜艳能量色与暗色背景强烈对比",
            "composition": "宽幅电影构图，仰角仰望人物",
            "mood": "史诗战斗强度，令人敬畏的力量感",
            "motion": "动态战斗姿势，能量释放，飘动衣物",
        },
    },
    {
        "name": "今敏 Satoshi Kon",
        "category": "心理系",
        "linework": "realistic proportions, psychological distortion elements",
        "shading": "realistic shading with surreal distortions",
        "lighting": "dramatic high contrast, psychological tension lighting",
        "palette": "desaturated reality tones with sudden vivid intrusions",
        "composition": "disorienting cuts, mirror reflections, layered reality",
        "mood": "psychological thriller, blurred reality and dream, unsettling",
        "motion": "sudden stillness, disorienting movement, trance-like",
        "background_detail": "overlapping scenes, fragmented environment, reality glitches",
        "keywords": ["Satoshi Kon style", "psychological surrealism", "reality distortion", "high contrast dramatic", "fragmented composition"],
        "zh_summary": "今敏风：心理悬疑、虚实交错、高对比、碎片构图",
        "zh_details": {
            "linework": "写实比例，融入心理扭曲元素",
            "shading": "写实明暗中穿插超现实变形",
            "lighting": "戏剧性强对比，心理张力灯光",
            "palette": "低饱和现实色调，突然插入鲜艳色彩",
            "composition": "迷失方向的切换，镜中映像，现实分层叠加",
            "mood": "心理惊悚，现实与梦境的模糊，令人不安",
            "motion": "突然的静止，迷失感运动，恍惚状态",
        },
    },
    {
        "name": "细田守 Mamoru Hosoda",
        "category": "家族温情系",
        "linework": "clean simple outlines, expressive character design",
        "shading": "flat simple shading, warm gentle color blocks",
        "lighting": "warm natural light, summer daylight, gentle indoor light",
        "palette": "warm whites, summer greens, golden sunlight, comfortable tones",
        "composition": "wide establishing environment, family group framing",
        "mood": "summer nostalgia, family warmth, bittersweet growing up",
        "motion": "running through nature, playful family scene",
        "background_detail": "detailed summer environment, digital world contrast, warm domestic interior",
        "keywords": ["Mamoru Hosoda style", "warm natural light", "summer atmosphere", "flat shading", "family scene"],
        "zh_summary": "细田守风：夏日温暖、家庭情感、干净简洁画风",
        "zh_details": {
            "linework": "干净简洁的轮廓，表现力强的角色设计",
            "shading": "简洁平涂明暗，温暖柔和色块",
            "lighting": "温暖自然光，夏日阳光，柔和室内光",
            "palette": "温暖白色，夏日绿，金色阳光，舒适色调",
            "composition": "宽阔环境建立镜头，家庭群像构图",
            "mood": "夏日怀旧，家庭温情，成长的甜蜜苦涩",
            "motion": "在自然中奔跑，嬉戏的家庭场景",
        },
    },
    {
        "name": "Production I.G 科幻",
        "category": "科幻系",
        "linework": "precise mechanical outlines, detailed technology elements",
        "shading": "cool tone shading, metallic surface rendering",
        "lighting": "night scene lighting, neon reflections on wet pavement, cool blue cast",
        "palette": "cold blues, cyan, dark grey, neon accent colors",
        "composition": "top-down city overview, cyberpunk street level",
        "mood": "mysterious philosophical, dystopian introspection",
        "motion": "slow deliberate movement, rooftop standing silhouette",
        "background_detail": "rainy cyberpunk cityscape, dense urban skyline, detailed mechanical environment",
        "keywords": ["Production I.G style", "night scene lighting", "cool moonlight", "cyberpunk city", "neon reflection"],
        "zh_summary": "Production I.G风：赛博科幻夜景、冷蓝调、哲思氛围",
        "zh_details": {
            "linework": "精准机械性描线，技术细节繁复",
            "shading": "冷色调明暗，金属表面渲染",
            "lighting": "夜景灯光，湿地面霓虹反射，冷蓝色调",
            "palette": "冷蓝色、青色、深灰、霓虹点缀",
            "composition": "都市俯瞰全景，赛博街道视角",
            "mood": "神秘哲思，反乌托邦内省",
            "motion": "缓慢沉稳的动作，屋顶上的孤独剪影",
        },
    },
    {
        "name": "WIT Studio 史诗感",
        "category": "史诗系",
        "linework": "bold expressive outlines, rough energy strokes",
        "shading": "dramatic dark shading, heavy shadow areas",
        "lighting": "dramatic overcast sky light, harsh directional light",
        "palette": "dark earth tones, grey-green, muted desaturated with contrast bursts",
        "composition": "extreme low angle looking up, massive scale contrast",
        "mood": "oppressive dread, desperate battle, epic tragedy",
        "motion": "desperate running, mid-battle action, vertical scale movement",
        "background_detail": "rough stone architecture, dark overcast sky, gritty atmospheric haze",
        "keywords": ["WIT Studio style", "dramatic shadow", "dark fantasy", "low angle anime", "epic scale contrast"],
        "zh_summary": "WIT Studio风：史诗压迫感、极端仰角、暗色调战斗氛围",
        "zh_details": {
            "linework": "粗犷有力的描线，粗糙能量感笔触",
            "shading": "戏剧性暗调明暗，大面积阴影区",
            "lighting": "阴沉天空漫射光，强烈方向性硬光",
            "palette": "深沉大地色，灰绿色调，低饱和与爆发性对比",
            "composition": "极端仰角仰望，巨大规模对比",
            "mood": "压迫性恐惧，绝望战斗，史诗悲剧",
            "motion": "绝望奔跑，激战中的动作，垂直规模感运动",
        },
    },
    {
        "name": "MAPPA 暗色压迫",
        "category": "暗黑系",
        "linework": "high detail sharp outlines, gritty texture",
        "shading": "deep dark shadows, high contrast rendering",
        "lighting": "hard dramatic lighting, dark environment with isolated light sources",
        "palette": "dark desaturated base with vivid energy color accents",
        "composition": "diagonal dynamic composition, extreme angles",
        "mood": "intense psychological pressure, dark despair, visceral impact",
        "motion": "violent explosive action, broken posture",
        "background_detail": "dark urban environment, cursed energy visual, heavy shadow and grime",
        "keywords": ["MAPPA style", "dramatic shadow", "dark fantasy", "high contrast", "diagonal composition"],
        "zh_summary": "MAPPA风：极高对比、暗黑压迫、高细节战斗场景",
        "zh_details": {
            "linework": "高度细节锐利描线，粗粝质感",
            "shading": "深邃阴影，高对比渲染",
            "lighting": "强硬戏剧性打光，暗色环境中的孤立光源",
            "palette": "低饱和暗色底色，鲜艳能量色点缀",
            "composition": "对角线动感构图，极端角度",
            "mood": "强烈心理压迫，黑暗绝望，内脏感冲击",
            "motion": "暴力爆发性动作，破碎姿态",
        },
    },
    {
        "name": "Bones 热血动作",
        "category": "热血系",
        "linework": "dynamic expressive outlines, action-oriented line work",
        "shading": "bright clean cel shading, clear highlight and shadow",
        "lighting": "bright open lighting, clear midday light, dramatic action burst",
        "palette": "vibrant primary colors, bright vivid, clean white highlights",
        "composition": "dynamic action framing, mid-motion freeze frame",
        "mood": "triumphant battle energy, heroic spirit, intense focus",
        "motion": "mid-air combat pose, speed motion blur, power release",
        "background_detail": "speed lines, impact visual effects, urban or arena environment",
        "keywords": ["BONES anime style", "cel shading", "vibrant saturated colors", "dynamic action", "bright clean lighting"],
        "zh_summary": "Bones风：明快热血、干净赛璐璐、英雄动作场面",
        "zh_details": {
            "linework": "动感表现性描线，动作导向笔触",
            "shading": "明快干净赛璐璐，清晰高光阴影分界",
            "lighting": "明亮开阔的光，清晰正午光，动作爆发光效",
            "palette": "鲜艳原色，明亮饱和，干净白色高光",
            "composition": "动感动作构图，运动定格帧",
            "mood": "胜利战斗能量，英雄精神，高度专注",
            "motion": "空中战斗姿势，速度动态模糊，力量释放",
        },
    },
    {
        "name": "Science SARU 实验风",
        "category": "艺术实验系",
        "linework": "loose fluid irregular outlines, hand-drawn experimental feel",
        "shading": "flat color with texture overlays, painterly irregular shading",
        "lighting": "bold flat lighting, psychedelic color light, stage performance lighting",
        "palette": "bold flat color blocks, psychedelic color contrast, unconventional palette",
        "composition": "distorted exaggerated perspective, fluid dynamic composition",
        "mood": "chaotic creative energy, fluid surreal imagination",
        "motion": "fluid rubber-limb motion, extreme exaggeration",
        "background_detail": "abstract painterly backgrounds, bold graphic texture, graffiti-like elements",
        "keywords": ["Science SARU style", "thick paint", "saturated vivid", "exaggerated wide angle", "flat color blocks"],
        "zh_summary": "Science SARU风：流体变形、大胆色块、实验性构图",
        "zh_details": {
            "linework": "松散流动不规则描线，手绘实验感",
            "shading": "平涂加纹理叠加，绘画感不规则明暗",
            "lighting": "大胆平光，迷幻色彩光源，舞台表演灯光",
            "palette": "大胆平涂色块，迷幻色彩撞色，非常规调色",
            "composition": "扭曲夸张透视，流体动感构图",
            "mood": "混乱创造能量，流动超现实想象",
            "motion": "流体橡皮肢体动作，极度夸张",
        },
    },
    {
        "name": "Madhouse 电影奇幻",
        "category": "奇幻系",
        "linework": "detailed refined outlines, cinematic quality",
        "shading": "painterly cinematic shading, detailed environment rendering",
        "lighting": "soft ambient diffused light, fantasy magical light sources",
        "palette": "pastel fantasy tones, soft magical colors, muted elegant palette",
        "composition": "wide fantasy landscape, character in vast environment",
        "mood": "lonely melancholy, quiet fantasy wonder, serene grandeur",
        "motion": "slow contemplative movement, standing in landscape",
        "background_detail": "vast fantasy landscape, wildflower fields, magical particle effects",
        "keywords": ["Madhouse style", "soft ambient light", "pastel soft", "fantasy landscape", "detailed background"],
        "zh_summary": "Madhouse风：电影质奇幻、柔和光、宏大孤独场景",
        "zh_details": {
            "linework": "精细精炼的描线，电影级品质",
            "shading": "绘画质感电影明暗，精细环境渲染",
            "lighting": "柔和漫射环境光，奇幻魔法光源",
            "palette": "粉彩奇幻色调，柔和魔法色，优雅哑光调色",
            "composition": "宽阔奇幻景观，人物置身广袤天地中",
            "mood": "孤独忧郁，静谧奇幻惊奇，宁静磅礴",
            "motion": "缓慢沉思性运动，屹立于景观中",
        },
    },
    {
        "name": "Shaft 强风格构图",
        "category": "强风格系",
        "linework": "stylized geometric outlines, sharp angular design",
        "shading": "flat stylized shading, strong graphic contrast",
        "lighting": "strong directional light, stark shadow patterns, graphic light design",
        "palette": "high contrast black and white accents, bold color pops",
        "composition": "tilted dutch angle, extreme close-up, screen-filling character",
        "mood": "stylish tension, intellectual drama, visually provocative",
        "motion": "dramatic head tilt, sudden pose shift",
        "background_detail": "abstract minimalist backgrounds, stark geometric patterns, blank space",
        "keywords": ["Shaft anime style, surreal head tilt", "dutch angle", "high contrast", "minimalist background", "anime portrait"],
        "zh_summary": "Shaft风：极端构图、高对比强风格、知性张力",
        "zh_details": {
            "linework": "风格化几何描线，锐利棱角设计",
            "shading": "平涂风格化明暗，强烈图形对比",
            "lighting": "强烈方向性光，鲜明阴影图案，图形化光线设计",
            "palette": "高对比黑白点缀，大胆色彩爆破",
            "composition": "斜角荷兰角，极端特写，占满画面的人物",
            "mood": "时髦张力，知性戏剧感，视觉挑衅",
            "motion": "戏剧性头部倾斜，突然的姿态切换",
        },
    },
    {
        "name": "CLAMP 华丽装饰",
        "category": "少女系",
        "linework": "elegant elongated thin outlines, ornate decorative detail",
        "shading": "delicate gradient shading, sparkle and glow effects",
        "lighting": "soft magical glow, sparkle light sources, gentle ambient",
        "palette": "elegant jewel tones, soft magical colors, gold and white accents",
        "composition": "centered portrait, symmetrical composition, flowing cloth framing",
        "mood": "elegant romance, magical destiny, graceful drama",
        "motion": "elegant flowing pose, cloth billowing, graceful reach",
        "background_detail": "ornate decorative patterns, sakura petals, sparkle particles",
        "keywords": ["CLAMP style", "cel shading", "pastel soft", "sparkle effect", "symmetrical composition"],
        "zh_summary": "CLAMP风：华丽装饰感、优雅少女情感、闪光粒子",
        "zh_details": {
            "linework": "优雅纤细拉长的描线，华丽装饰细节",
            "shading": "精致渐变明暗，闪光与发光效果",
            "lighting": "柔和魔法光晕，闪光光源，温柔环境光",
            "palette": "优雅宝石色调，柔和魔法色，金色与白色点缀",
            "composition": "居中人物肖像，对称构图，飘动布料框景",
            "mood": "优雅浪漫，魔法宿命，端庄戏剧感",
            "motion": "优雅流动姿势，布料飘动，优美伸手",
        },
    },
    {
        "name": "日常柔光 Slice of Life",
        "category": "日常系",
        "linework": "clean soft outlines, gentle character design",
        "shading": "soft warm cel shading, minimal shadow",
        "lighting": "soft window light, warm afternoon sunlight, gentle diffused",
        "palette": "warm pastel colors, cream whites, soft pinks and yellows",
        "composition": "everyday interior setting, character in comfortable environment",
        "mood": "peaceful everyday warmth, gentle quiet happiness",
        "motion": "sitting comfortably, sipping tea, reading quietly",
        "background_detail": "cozy interior detail, soft bokeh, warm natural light through curtain",
        "keywords": ["KyoAni style", "soft ambient light", "warm sunset", "daily life", "pastel soft"],
        "zh_summary": "日常柔光风：温柔室内光、惬意日常、暖色粉彩调",
        "zh_details": {
            "linework": "干净柔和描线，温柔角色设计",
            "shading": "柔和暖色赛璐璐，阴影极少",
            "lighting": "柔和窗光，温暖午后阳光，轻柔漫射",
            "palette": "温暖粉彩，奶油白，柔和粉黄色调",
            "composition": "日常室内场景，人物置于舒适环境",
            "mood": "平静日常温暖，温柔宁静的幸福感",
            "motion": "舒适地坐着，品茶，静静阅读",
        },
    },
    {
        "name": "机甲硬科幻 Hard Mecha",
        "category": "机甲系",
        "linework": "precise mechanical outlines, hard surface panel detail",
        "shading": "metallic surface shading, specular highlight, industrial rendering",
        "lighting": "harsh industrial lighting, dramatic underlighting, energy glow",
        "palette": "cold metallic greys, electric blue accents, warning orange",
        "composition": "low angle looking up at mecha, massive scale emphasis",
        "mood": "cold mechanical power, epic scale, heroic determination",
        "motion": "powering up stance, launching sequence",
        "background_detail": "industrial launch facility, space background, mechanical detail",
        "keywords": ["hard sci-fi mecha", "cel shading", "dramatic shadow", "low angle anime", "metallic sheen"],
        "zh_summary": "机甲硬科幻风：精密机械感、冷金属光、史诗仰角",
        "zh_details": {
            "linework": "精准机械描线，硬表面装甲板细节",
            "shading": "金属表面明暗，高光反射，工业渲染",
            "lighting": "强烈工业光，戏剧性仰射光，能量发光",
            "palette": "冷金属灰，电光蓝点缀，警示橙色",
            "composition": "仰角仰望机甲，强调巨大规模感",
            "mood": "冷峻机械力量，史诗规模，英雄决意",
            "motion": "蓄力待机姿势，发射准备序列",
        },
    },
    {
        "name": "暗黑奇幻 Dark Fantasy",
        "category": "暗黑奇幻系",
        "linework": "detailed dark outlines, gothic ornate detail",
        "shading": "deep shadow shading, dark dramatic rendering",
        "lighting": "ominous underlighting, torch glow, cold moonlight",
        "palette": "dark gothic colors, deep purples, crimson, dark gold",
        "composition": "dramatic low angle, ominous silhouette against dark sky",
        "mood": "dark foreboding, gothic horror atmosphere, sinister power",
        "motion": "imposing standing pose, dark cape billowing",
        "background_detail": "gothic castle environment, dark sky, bone and shadow details",
        "keywords": ["dark fantasy", "dramatic shadow", "dark gothic atmosphere", "gothic atmosphere", "low angle anime"],
        "zh_summary": "暗黑奇幻风：哥特氛围、深紫黑暗调、邪恶力量感",
        "zh_details": {
            "linework": "细密暗色描线，哥特华丽装饰细节",
            "shading": "深邃阴影明暗，暗色戏剧渲染",
            "lighting": "不祥的仰射灯光，火炬光晕，冷色月光",
            "palette": "暗色哥特调，深紫色、深红色、暗金色",
            "composition": "戏剧性仰角，黑暗天空前的不祥剪影",
            "mood": "黑暗预感，哥特恐怖氛围，邪恶力量感",
            "motion": "压迫性的站立姿态，暗色斗篷随风飘动",
        },
    },
]
