"""
中文翻译映射表 + kw_to_zh 工具函数
（仅用于预览，不参与 prompt 生成）
"""

# 基础参数选项的中文描述  {英文关键词: 中文描述}
ZH_PARAM_VALUES = {
    # 镜头焦距
    "14mm": "14mm 超广角",
    "24mm": "24mm 广角",
    "35mm": "35mm 标准广角",
    "50mm": "50mm 标准",
    "85mm": "85mm 人像",
    "100mm": "100mm 微距",
    "135mm": "135mm 长焦",
    "200mm": "200mm 远摄",
    "400mm": "400mm 超长焦",
    # 光圈
    "f/1.2": "f/1.2 极浅景深",
    "f/1.4": "f/1.4 极浅景深",
    "f/1.8": "f/1.8 浅景深人像",
    "f/2.0": "f/2.0 大光圈",
    "f/2.8": "f/2.8 电影常用",
    "f/4":   "f/4 均衡",
    "f/5.6": "f/5.6 通用",
    "f/8":   "f/8 标准风景",
    "f/11":  "f/11 大景深",
    "f/16":  "f/16 极深景深",
    # ISO
    "ISO 100": "ISO 100 极低噪点",
    "ISO 200": "ISO 200 低噪点",
    "ISO 400": "ISO 400 正常",
    "ISO 800": "ISO 800 略有噪点",
    "ISO 1600": "ISO 1600 高感光",
    "ISO 3200": "ISO 3200 高噪点",
    "ISO 6400": "ISO 6400 极高噪点",
    # 快门
    "1/4000s": "1/4000s 超高速冻结",
    "1/2000s": "1/2000s 高速运动",
    "1/1000s": "1/1000s 快速冻结",
    "1/500s":  "1/500s 运动捕捉",
    "1/250s":  "1/250s 通用快门",
    "1/125s":  "1/125s 较快快门",
    "1/60s":   "1/60s 较慢快门",
    "1s":      "1s 长曝光",
    "5s":      "5s 长曝光",
    "30s":     "30s 超长曝光",
    # 特殊角度
    "dutch angle": "荷兰角（斜角）",
    "over the shoulder": "过肩拍摄",
    "aerial drone shot": "航拍无人机",
    "pov shot": "第一人称视角",
    "through glass": "透过玻璃",
    "reflection shot": "镜像反射",
    # 镜头稳定
    "handheld": "手持晃动",
    "steadicam": "斯坦尼康稳定",
    "tripod": "三脚架固定",
    "dolly shot": "推轨移动",
    "crane shot": "摇臂升降",
    "gimbal stabilized": "电子稳定",
    # 胶片格式
    "anamorphic 2.39:1": "变形宽幕镜头",
    "spherical": "球面标准",
    "IMAX 70mm": "大画幅IMAX",
    "Super 35mm": "超35mm电影格式",
    "16mm film": "16mm胶片",
    "8mm vintage": "8mm复古家用",
    # 构图方式
    "rule of thirds": "三分法构图",
    "centered": "居中对称构图",
    "leading lines": "引导线构图",
    "frame within frame": "框中框构图",
    "symmetrical": "对称构图",
    "golden ratio": "黄金比例",
    "negative space": "留白构图",
    # 景深
    "shallow depth of field": "浅景深（背景虚化）",
    "deep depth of field": "深景深（全清晰）",
    "medium depth of field": "中等景深",
    # 相机机型
    "shot on Sony A7IV": "拍摄设备：索尼 A7IV",
    "shot on Canon EOS R5": "拍摄设备：佳能 EOS R5",
    "shot on Nikon Z9": "拍摄设备：尼康 Z9",
    "shot on Fujifilm X-T5": "拍摄设备：富士 X-T5",
    "shot on Leica M11": "拍摄设备：徕卡 M11",
    "shot on Hasselblad X2D": "拍摄设备：哈苏 X2D",
    "shot on Arri Alexa Mini": "拍摄设备：Arri Alexa Mini（电影机）",
    "shot on DJI Air 3": "拍摄设备：大疆 Air 3（无人机）",
    "shot on GoPro Hero 12": "拍摄设备：GoPro Hero 12（运动相机）",
    # 打光风格
    "natural light": "自然光",
    "golden hour": "黄金时段（日出日落）",
    "blue hour": "蓝调时段（黎明黄昏）",
    "Rembrandt lighting": "伦勃朗光（经典人像）",
    "rim lighting": "轮廓光（逆光勾边）",
    "softbox lighting": "柔光箱（均匀柔和）",
    "hard light": "硬光（强对比）",
    "backlight": "逆光",
    # 色调风格
    "teal and orange": "青橙色调（好莱坞风）",
    "warm tones": "暖调",
    "cool tones": "冷调",
    "black and white": "黑白",
    "desaturated": "低饱和",
    "vivid colors": "高饱和鲜艳",
    "vintage": "复古",
    # 画面比例
    "16:9": "16:9 宽屏",
    "4:3":  "4:3 传统",
    "1:1":  "1:1 方形",
    "2.39:1": "2.39:1 宽银幕",
    "9:16": "9:16 竖屏",
    "4:5":  "4:5 社交媒体",
    # 品质
    "4K": "4K高清",
    "8K": "8K超清",
    "photorealistic": "照片级写实",
    "highly detailed": "高度细节",
    "sharp focus": "锐利对焦",
    "RAW photo": "RAW格式",
    # 二次元 — 构图视角
    "standard anime shot": "标准动画视角",
    "low angle anime": "仰视构图",
    "top-down anime": "俯视构图",
    "anime portrait": "近距人物视角",
    "exaggerated wide angle": "极大广角夸张视角",
    "dynamic diagonal composition": "对角线动态构图",
    "symmetrical composition": "对称构图",
    "over the shoulder anime": "过肩构图",
    "negative space composition": "大留白构图",
    # 渲染风格
    "cel shading": "赛璐珞风格",
    "anime key visual": "动画关键帧风格",
    "watercolor illustration": "水彩插画",
    "thick paint": "厚涂风格",
    "sketch style": "素描风格",
    "pixel art": "像素风",
    "flat design": "扁平设计",
    # 画风词
    "Studio Ghibli style": "吉卜力工作室风格",
    "KyoAni style": "京都动画风格",
    "Makoto Shinkai style": "新海诚风格",
    "Trigger style": "Trigger工作室风格",
    "A-1 Pictures style": "A-1 Pictures风格",
    "Ufotable style": "Ufotable工作室风格",
    "Wit Studio style": "Wit Studio风格",
    "MAPPA style": "MAPPA工作室风格",
    "Production I.G style": "Production I.G风格",
    "Gainax style": "Gainax工作室风格",
    "Madhouse style": "Madhouse工作室风格",
    "Science SARU style": "Science SARU风格",
    "Tatsuki Fujimoto style": "藤本树风格",
    # 动画打光
    "anime sunlight": "动画阳光",
    "rim light with glow": "发光轮廓光",
    "flat lighting": "扁平光",
    "dramatic shadow": "戏剧性阴影",
    "soft ambient light": "柔和环境光",
    "night scene lighting": "夜景灯光",
    # 画面色调
    "saturated vivid": "高饱和鲜艳",
    "pastel soft": "粉彩柔和",
    "dark fantasy": "暗黑奇幻",
    "warm sunset": "温暖日落",
    "cool moonlight": "冷蓝月光",
    "neon cyberpunk": "霓虹赛博朋克",
    # 情绪氛围
    "peaceful and gentle": "温柔宁静",
    "tense and dramatic": "紧张震撼",
    "daily life": "日常轻松",
    "lonely melancholy": "孤独忧郁",
    "epic and grand": "史诗磅礴",
    "mysterious": "神秘",
    # 景别
    "extreme wide shot": "超远景",
    "wide shot": "远景",
    "medium shot": "中景",
    "close-up": "近景",
    "extreme close-up": "特写",
    "macro shot": "微距",
    "extreme macro": "超微距",
    # 俯仰角
    "worm's eye view, extreme low angle": "虫视极端仰角",
    "low angle shot": "低角仰拍",
    "slight low angle": "轻微仰拍",
    "eye level shot": "平视",
    "slight high angle": "轻微俯拍",
    "high angle shot": "高角俯拍",
    "bird's eye view, overhead shot": "鸟瞰/顶视",
    # 方位角
    "front view, facing camera directly": "正面",
    "front-left three-quarter view": "左前45°",
    "left side profile view": "正左侧",
    "rear-left three-quarter view": "左后45°",
    "back view, shot from behind": "正背面",
    "rear-right three-quarter view": "右后45°",
    "right side profile view": "正右侧",
    "front-right three-quarter view": "右前45°",
    # 光源方向
    "front lighting": "前方正面光",
    "front-right lighting": "右前方光",
    "right side lighting": "右侧光",
    "back-right lighting": "右后方光",
    "back lighting": "背光",
    "back-left lighting": "左后方光",
    "left side lighting": "左侧光",
    "front-left lighting": "左前方光",
    "overhead top-down lighting": "顶部俯射光",
    "underlighting from below": "底部仰射光",
    "high front lighting": "高位前方光",
    "high front-right lighting": "高位右前光",
    "high right side lighting": "高位右侧光",
    "high back-right lighting": "高位右后光",
    "high back lighting": "高位背光",
    "high back-left lighting": "高位左后光",
    "high left side lighting": "高位左侧光",
    "high front-left lighting": "高位左前光",
    "low front lighting": "低位前方光",
    "low front-right lighting": "低位右前光",
    "low right side lighting": "低位右侧光",
    "low back-right lighting": "低位右后光",
    "low back lighting": "低位背光",
    "low back-left lighting": "低位左后光",
    "low left side lighting": "低位左侧光",
    "low front-left lighting": "低位左前光",
    "rim light": "轮廓光（边缘补光）",
    # 光源颜色
    "white": "白色光",
    "warm white": "暖白光",
    "golden": "金黄色光",
    "orange": "橙色光",
    "red-orange": "红橙色光",
    "red": "红色光",
    "pink": "粉色光",
    "cool blue": "冷蓝光",
    "soft blue": "柔和蓝光",
    "cyan": "青色光",
    "green": "绿色光",
    "purple": "紫色光",
    "colored": "彩色光",
    # 动作/动态
    "walking slowly": "缓步行走",
    "running at full speed": "全速奔跑",
    "jumping mid-air": "腾空跳跃",
    "standing still, slight breeze": "静立，微风轻拂",
    "dancing gracefully": "优雅起舞",
    "reaching out hand": "伸手向前",
    "looking back over shoulder": "回眸转身",
    "crouching low": "低伏蹲姿",
    "falling": "下坠/跌落",
    "floating": "悬浮漂浮",
    "sitting cross-legged": "盘腿而坐",
    "kneeling": "跪姿",
    "lying down": "躺卧",
    "looking up at sky": "仰望天空",
    "arms raised": "双臂上扬",
    # 质量词块（实拍）
    "masterpiece": "大师之作",
    "best quality": "最佳质量",
    "award winning photography": "获奖摄影",
    # 质量词块（动画）
    "ultra detailed": "超高细节",
    "official art": "官方插画品质",
    "anime illustration": "动画插画",
    "highres": "高分辨率",
    "beautiful detailed eyes": "精美眼睛细节",
    "delicate linework": "精细线稿",
    # 细节质感（实拍）
    "skin pores visible": "皮肤毛孔可见",
    "fabric weave detail": "织物编织纹理",
    "metallic sheen": "金属光泽",
    "wet surface": "湿润表面质感",
    "rough stone texture": "粗糙石质纹理",
    "glass reflections": "玻璃折射反光",
    "wood grain": "木纹",
    "leather texture": "皮革质感",
    # 细节质感（动画）
    "cel shading outline": "赛璐璐描边",
    "flat color blocks": "平涂色块",
    "gradient hair shading": "发丝渐变明暗",
    "sparkle effect": "闪光特效",
    "soft shadow rendering": "柔和阴影渲染",
    "glowing aura": "发光光晕",
    "detailed eye catchlight": "眼睛高光细节",
    "screen tone pattern": "网点纸效果",
    # 色彩补充（实拍）
    "vibrant saturated colors": "高饱和鲜艳",
    "muted desaturated palette": "低饱和哑光",
    "monochromatic": "单色调",
    "complementary color contrast": "互补色对比",
    "analogous warm tones": "暖色系",
    "cool color palette": "冷色系",
    # 色彩补充（动画）
    "pastel color palette": "马卡龙粉彩色",
    "neon cyberpunk colors": "霓虹赛博配色",
    "sakura pink tones": "樱花粉调",
    "dark gothic palette": "暗黑哥特调",
    "golden sunset gradient": "黄昏金橙渐变",
    "ocean blue tones": "海洋蓝调",
    # 风格词块（动画）
    "retro anime 80s": "复古80年代动画风",
    # 美学词块（实拍）
    "film noir": "黑色电影",
    "cyberpunk": "赛博朋克",
    "steampunk": "蒸汽朋克",
    "baroque": "巴洛克",
    "minimalist": "极简主义",
    "surrealism": "超现实主义",
    "impressionism": "印象派",
    "pop art": "波普艺术",
    # 美学词块（动画）
    "retro 80s anime": "复古80年代风",
    "wuxia xianxia": "武侠仙侠",
    "lovecraftian horror": "克苏鲁恐怖",
    "post-apocalyptic wasteland": "末世废土",
    "dreamy fairy tale": "梦幻童话",
    "dark fantasy": "黑暗奇幻",
    "hard sci-fi mecha": "机甲硬科幻",
    # 情绪词块（实拍）
    "dramatic": "戏剧性",
    "serene": "宁静",
    "melancholic": "忧郁",
    "energetic": "充满活力",
    "romantic": "浪漫",
    "tense": "紧张",
    "nostalgic": "怀旧",
    # 情绪词块（动画）
    "healing and gentle": "治愈温柔",
    "chuunibyou dramatic": "中二病戏剧感",
    "mono no aware": "物哀",
    "intense battle spirit": "热血战斗魂",
    "everyday slice of life": "日常轻松",
    "dark and brooding": "暗黑沉思",
    "whimsical fantasy": "奇幻异想",
    "bittersweet": "苦中带甜",
    # 新增画风词
    "J.C.Staff style": "J.C.Staff工作室风格",
    "CloverWorks style": "CloverWorks工作室风格",
    "WIT Studio style": "WIT Studio风格",
    "BONES anime style": "BONES动画风格",
    "aspect ratio 16:9": "16:9 宽屏比例",
    "aspect ratio 4:3": "4:3 传统比例",
    "aspect ratio 1:1": "1:1 方形",
    "aspect ratio 2.39:1": "2.39:1 宽银幕",
    "aspect ratio 9:16": "9:16 竖屏",
    "aspect ratio 4:5": "4:5 社交媒体",
    "aspect ratio 2:3": "2:3 竖版",
    "aspect ratio 3:2": "3:2 横版",
}

# 参数名中文标签映射（用于预览分组标题）
ZH_PARAM_NAMES = {
    "镜头焦距": "镜头焦距",
    "光圈": "光圈",
    "ISO": "ISO 感光度",
    "快门速度": "快门速度",
    "特殊角度": "特殊角度",
    "镜头稳定": "稳定方式",
    "胶片格式": "胶片格式",
    "构图方式": "构图方式",
    "景深": "景深",
    "相机机型": "拍摄设备",
    "打光风格": "打光风格",
    "色调风格": "色调风格",
    "画面比例": "画面比例",
    "品质": "画质要求",
    "构图视角": "构图视角",
    "渲染风格": "渲染风格",
    "画风词": "画风来源",
    "动画打光": "动画打光",
    "画面色调": "画面色调",
    "情绪氛围": "情绪氛围",
}


def kw_to_zh(kw: str) -> str:
    """将英文关键词转换为中文描述，找不到则返回原词"""
    kw_stripped = kw.strip()
    if kw_stripped in ZH_PARAM_VALUES:
        return ZH_PARAM_VALUES[kw_stripped]
    for en, zh in ZH_PARAM_VALUES.items():
        if kw_stripped.startswith(en) or en.startswith(kw_stripped):
            return zh
    return kw_stripped
